name: CI

# Controls when the workflow will run
on:

 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
       node: [18, 20]
   steps:
     - uses: actions/checkout@v4

     - name: Setup Node ${{ matrix.node }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node }}

     - name: Print environment
       run: |
         node -v
         echo "OS: $RUNNER_OS
